### ISSUE TITLE
UI: ListBox control

### ISSUE THREAD

**Issue by seanpaultaylor** [gameplay3d/GamePlay#1323]

**Comment by rgdev78** [comment]
I love this idea but I was wondering what is the current status of this or will it be pushed to the 3.5.0 milestone?

**Comment by seanpaultaylor** [comment]
Looks like it.

**Comment by gabereiser** [comment]
if this doesn't have any traction, I'll code it up.

**Comment by rcmaniac25** [comment]
I haven't done anything on this... so it's fine with me.
