### ISSUE TITLE
External Dependencies Repo

### ISSUE THREAD

**Issue by seanpaultaylor** [gameplay3d/GamePlay#1606]
Here is where the new repository will be:
<url>https://github.com/gameplay3d/GamePlay-deps</url>

This will have all the source code for the external-deps libraries with cross-compiler support for building static libs with CMake on each desktop platform for each on the following platforms/architectures:

windows (x64)
linux (x86_64)
macosx (x86_64)
ios (armv7, armv7s, arm64, i386, x86_64)
android (armeabi-v7a, x86)

Here is an assumed new repository structure:
GamePlay-deps
---- box2d
---- bullet
---- freetype
---- glew
---- icu
---- lua
---- ogg
---- openal
---- png
---- tinyxml
---- theora
---- sqlite
---- vorbis
---- zlib
---- VERSIONS
---- CMakeLists.txt

Each library folder will contain the untouched source contents from their official releases + their own CMakeLists.txt file in each.

**Comment by nlandry** [comment]
A couple more changes still needed:

- Lower-case for all platform names
- Remove the extra "bullet" include directory (that way we only need a single external-deps include path)

**Comment by seanpaultaylor** [comment]
Looks great!
