### ISSUE TITLE
Serialization Support

### ISSUE THREAD

**Issue by rgngl** [gameplay3d/GamePlay#1618]
This could be handy for saving game settings and state. I think variable elements in the property class can be used to save dynamic data to configuration files. If it's OK, I can do this and send a patch.

**Comment by VinnyVicious** [comment]
Scene::save would be great! :+1:

**Comment by hammeron-art** [comment]
I'm also in need for that in my project.
The way I'll implement it:

```cpp
class Serializer
{
public:

	SameErrorCode load(const char* path);
	SameErrorCode save(const char* path);

	// Rename get... methods to read...?

	// ...

	void writeInt(const char* name, const int value);
	void writeString(const char* name, const char* value);

	// ...
};

// The plan is to implement it for any class than can use a property file
class Serializable
{
public:
	virtual Serializer* serialize();
	virtual SameErrorCode unserialize(Serializer* serializerObj);
};

// And use it like:
// Save
Serializer* serializer = material->serialize();
serializer->save();

// Load
Serializer* settings;
settings->load("path");

material.unserialize(settings);
```

**Comment by seanpaultaylor** [comment]
This is now implemented. For now I submitted only in my branch. 
I still need to implement Serializable for several more classes to be able to read/write the scene.
I have enough completed that I can continue on to the editor work and start using it in the editor and implement as I go along.
