### ISSUE TITLE
 2D Physics support

### ISSUE THREAD

**Issue by seanpaultaylor** [gameplay3d/GamePlay#1631]
* Add new classes which are implemented with Box2D physics:
```
PhysicsController2D
PhysicsCollisionObject2D
PhysicsRigidBody2D
PhysicsConstraint2D
...
```
* Add PhysicsCollidable (new base class for  PhysicsCollisionObject and PhysicsCollisionObject2D)
* Change Node interface from setCollisionObject to setCollidable(PhysicsCollidable collidable);
* Add support to .physics file for PhysicsObject2D, PhysicsRigidBody2D, PhysicsConstraint2D, etc

**Comment by jose55** [comment]
Add 2d Physics support ?
Do I have to understand that there are no Physic classes for 2D at all in the stable release ?

**Comment by seanpaultaylor** [comment]
Correct. The external dependencies do have box2d integrated in though. We have not exposed and integration wrapper yet and bindings.

**Comment by jose55** [comment]
ok...  you are the owner of this project - gameplay !?!?
Only one person the owner ???
