### ISSUE TITLE
Throttling framerate

### ISSUE THREAD

**Issue by Gippoman** [gameplay3d/GamePlay#1642]
Since this is largely used on mobile it would be nice to have a call to limit the framerate ( battery life says thanks )

**Comment by seanpaultaylor** [comment]
Right now we have setVSync(bool) This sync for 60 fps. We could change this to an enum since its best to sync either 30 or 60 or none(go as fast as possible.

**Comment by Gippoman** [comment]
Im aware of the SetVSync(bool) function, but i guess more options are better? :D

**Comment by seanpaultaylor** [comment]
I agree that an option for 30FPS would be better aligned for mobile. Another option is for us to always run vsync = true at 30 fps on mobile and 60 on desktop.

**Comment by rgdev78** [comment]
I think the best approach would be to turn setVSync to an enum and have values for ( none, 1, 15, 30, 60 ) then set default to 30 as mobile devices are the primary target.

Most importantly: also have the C++ documentation and the doxygen documentation explain that "for best speed on any platform ( and particularly desktops choose 60 or none).  for battery saving on mobile devices choose 15 or 30.  Note: we added the option 1 for hardcore development alpha testing in some situations.

> ""Another option is for us to always run vsync = true at 30 fps on mobile and 60 on desktop. ""

 I rather like the option to run at 60 or none on mobile devices as an option :-)

**Comment by seanpaultaylor** [comment]
1 might be good for debugging. But not really necessary. 15 is basically useless.

**Comment by rgngl** [comment]
+1 from me for 1fps rendering for debugging purposes.
