### ISSUE TITLE
OpenAL problem

### ISSUE THREAD

**Issue by rgngl** [gameplay3d/GamePlay#1649]
Last time I checked, OpenAL implementation used on Android builds was this one: http://kcat.strangesoft.net/openal.html

With this version there's an issue in Android builds. When the application doesn't quit but instead goes to background, the application still holds the audio device open and pressing volume buttons still adjust the media volume - not the ring volume, as the user expects.

Apportable's OpenAL has extra methods `alcSuspend()` and `alcResume()` to avoid this problem.

So I suggest the OpenAL library in the external-deps should be replaced with the one from Apportable's repository(https://github.com/apportable/openal-soft) and `alcSuspend()` and `alcResume()` calls should be added in `AudioController::pause()` and `AudioController::resume()`.

They have the same licence so there shouldn't be any issues using it instead.

**Comment by seanpaultaylor** [comment]
We can just do the same changes for Android. I don't think changing entire version just to fix a bug is a good solution.

**Comment by seanpaultaylor** [comment]
Also, we use the kcat version for all platforms. That is the goal.
