### ISSUE TITLE
.scene support for loading properties support for sprite, tileset and text on nodes

### ISSUE THREAD

**Issue by seanpaultaylor** [gameplay3d/GamePlay#1650]
1. Finish support for loading properties from .scene files for:  sprite, tileset and text
2. Update samples-browser/SpriteSample to load everything from a .scene file and also show adding another few items programattically.

**Comment by seanpaultaylor** [comment]
Are you able to implement only the properties loading for now ? We want to release soon without the other features completed. We can push the .tmx to .scene to the next release.

**Comment by rcmaniac25** [comment]
Properties loading is done.

How soon would you need the tmx to scene? I can probably finish it in a day or two as I have most of the parsing done, so I just need to actually write the file. Though it wouldn't have gutter support.

**Comment by seanpaultaylor** [comment]
Ok. Please submit the Properties loading for now alone. Then work for finishing tmx loading for this week release. The gutters is an artists requirement for now.

**Comment by seanpaultaylor** [comment]
How are things coming along?
Can you for now, just update the SpriteSample to load from a .scene file and add a more full TileSet.
The goal for the sample is to show construction of the 2D sprite scene. Very minimal interaction.
So just keep a floor that is continuous left-right with lots of things around it and possible some spruites moving around it. 2D Physics will come later.

Then that would be enough and we can bump this specific .tmx to .scene encoder changes until next release. Unless your done ?

I plan to release tonight and @nlandry needs to build the final luagen and encoder binaries.

**Comment by rcmaniac25** [comment]
I'll just do that then. I kept planning to work on the encoder this week, but lots of school-stuff started up again, so I wasn't able to get to it.

**Comment by seanpaultaylor** [comment]
No problem. After that is completed and submitted, I will bug you to also update the section of the file formats for sprite, tileset and text:
http://gameplay3d.github.io/GamePlay/docs/file-formats.html

**Comment by seanpaultaylor** [comment]
Lets rename this one and you can submit against this Issue. I will create another issue and transfer the .tmx encoder name for it.

**Comment by rcmaniac25** [comment]
I'm a little late on the sample... and it only mimics the current sample implementation. But it at least helped me figure out what the output of the encoder should look like and additional things to load from Properties (Effect loading and setting frame sources for Sprites, possibly Animation loading support for Sprites, and ability to load child nodes from .scene's [which is an unrelated issue])

**Comment by rcmaniac25** [comment]
FYI, I have a working encoder with most if not all features working for .tmx to .scene conversion in my branch https://github.com/rcmaniac25/GamePlay/tree/encoder_2D.

It doesn't have gutters yet, needs a bit of cleanup, and only exports TileSets right now (I don't deal with "objects" and have yet to find anything aside from <imagelayer>s that are remotely Sprite based.

I'm going to have to do that work another day, but if you want to look and make any comments, please do so it's as-good-as possible for merging when I finish the rest of it.
