### ISSUE TITLE
Base.h includes everything and makes compilation slow

### ISSUE THREAD

**Issue by rgngl** [gameplay3d/GamePlay#1652]
Base.h includes all the headers ever used by Gameplay3D so, all the source files include every header file during compilation. Because of this a full build of Gameplay3D takes quite long. In fact, full builds happen quite often because both Xcode and Android ndk-build makes a full build from scratch every time the project files are touched, not to mention touching the Base.h triggers a full build too.

I think it wouldn't be so hard to make some refactoring there such as including bullet headers only from physics related classes or Lua includes only from scripting related classes.

STL headers are also quite big and I don't think they're needed to be included from every single source file.

**Comment by reven86** [comment]
This could also be fixed by using precompiled headers, not sure is it possible on Android though.

**Comment by seanpaultaylor** [comment]
Not a very high priority for the users/game developers. Our focus is on features for them right now and not the game framework team LOL

**Comment by rgngl** [comment]
I understand this is not really high priority thing but still the long build times sometimes become frustrating and become unproductive. Ccache takes care of the issue on Android but there's no alternative for Xcode builds yet. If there's anybody out there who got ccache working with Xcode I'll be happy to know.

**Comment by HardlineStudios** [comment]
I've adjusted my branch of GamePlay3D to use pre-compiled headers as MOST development happens on the PC side anyways. 

You can also do PCH with GCC as well.

**Comment by rgdev78** [comment]
in general I agree with Sean on where to put team focus with the Jan 30 release milestone approaching.

However; I'd like to give a big  __+1__  to this request as an exception the rule due to major enhancement to the overall development process ( long build times get annoying and i'm planning on possible mac/iOS dev later this year )

O:-)

**Comment by seanpaultaylor** [comment]
Are you building the engine all the time ?

**Comment by rgdev78** [comment]
Every so often i'll redownload from next branch and re-build the engine ( from scratch ) on Linux Mint 17.1 then add in my C++ code and pick up where Ieft off.

My current development process is to make modifications to one of the existing samples ( browser so far ) in the C++ to include my C++ game code.  I do this to explore and try to understand how the gameplay works as I get more into it.

but I was refering to is the thing that I do is run any debug install to my tablet every time I make a change.  Thus any enhancements to decrease that compile time will always be welcome and particularly as I create a really Big project with lots of parts.
