### ISSUE TITLE
FrameBuffer multisampling support

### ISSUE THREAD

**Issue by zakki** [gameplay3d/GamePlay#1682]
Current PostProcessSample renders to high resolution frame buffer, and shrinks it.
Multisampling support while off-screen rendering would be useful.

experimental code: https://github.com/zakki/GamePlay/compare/gameplay3d:next...offscreen-antialiasing

**Comment by amerkoleci** [comment]
Neat stuff, probably wont work under gles 2.0 but can be integrated for desktop gl ans futurw gles 3.1

**Comment by amerkoleci** [comment]
Why closing?

**Comment by seanpaultaylor** [comment]
No plans for this for a while.

**Comment by seanpaultaylor** [comment]
@amerkoleci . This actaully does work on some OpenGL ES 2.0 platforms with extensions.

**Comment by seanpaultaylor** [comment]
@zakki Can you add this in based on detecting support ?

**Comment by zakki** [comment]
I think current client code is a bit complicated. Do you have any good idea?
https://github.com/gameplay3d/GamePlay/compare/next...zakki:offscreen-antialiasing#diff-0577fc7a9d0ab2318fe0e501d7905853R105
