### ISSUE TITLE
error: The XML response contains invalid XML

### ISSUE THREAD

**Issue by Mikez2015** [gameplay3d/GamePlay#1687]
When I try download 
https://github.com/gameplay3d/GamePlay
use Tortoise SVN arter dowloading 1.506Gb files,  I got error: The XML response contains invalid XML
Screenshot:
![error](https://cloud.githubusercontent.com/assets/10583925/5792600/bbbfe222-9f4a-11e4-81fc-ea55a6acf50b.png)
:

**Comment by seanpaultaylor** [comment]
You need to use TortoiseGIT not TortoiseSVN.
This is an TortosieSVN issue.

**Comment by rgngl** [comment]
Github supports downloading github repos with a Subversion client too, but apparently this is either a TortoiseSVN or github problem. Not related to this project particularly.
