### ISSUE TITLE
Editor - Beta 1

### ISSUE THREAD

**Issue by seanpaultaylor** [gameplay3d/GamePlay#1696]
Cross-platform editor written in QT 5.6 (for Windows, MacOSX, Linux)

Beta 1 features:  
- New project wizard.
- Manage project assets.
- Scene hierarchy and basic node creation.
- Property editor for editing simple properties.
- Import FBX, TTF, PNG
- New serialization format
- Launch developer defined executable.
- Launch developer workspaces by opening C++ or Lua source files.

**Comment by sbrkopac** [comment]
This is great news, any chance of the snippet used to connect QT 5.4 to GP?

**Comment by billyquith** [comment]
Does this exist somewhere that we can look at it? Or is this just a plan?

**Comment by seanpaultaylor** [comment]
Yes sire. I am pretty busy working on this one....
![projectwizard](https://cloud.githubusercontent.com/assets/1127169/11128560/7b438382-8948-11e5-90d4-44f3811f7397.png)
![editor](https://cloud.githubusercontent.com/assets/1127169/11128563/81be40e4-8948-11e5-9a0e-4999410211fc.png)

**Comment by xthydra** [comment]
is it going to contain a scene editor?

**Comment by seanpaultaylor** [comment]
Yes. That's the plan. However, its a pretty big task so its gonna take a while to get things moving and I submit to the repo.

**Comment by K0j0** [comment]
This looks awesome!

**Comment by seanpaultaylor** [comment]
Thx. Work in progress... I will do my best to keep it clean and simple. 
I'm gonna try to get a similar feature set as possible to the Unity, except you can obviously double click you C++ code and immediately launch your workspaces in your favorite IDE and build your code there and then pop back and forth between assets and coding. It will also include a new project wizard and importing functionality so you don't need to use any existing command line tools if you choose not too.

**Comment by xthydra** [comment]
i was anxious that my terrain editor would be competing with your editor. thx for clarifying your intent.

**Comment by seanpaultaylor** [comment]
I will end up adding Terrain editing. But not until Beta 2 or 3.
@sgrenier Has alot of experience with this since he implemented one in the past in our previous game engine.

**Comment by billyquith** [comment]
Will this editor be open sourced as part of this gameplay3d? I'm trying to decide whether to use GP. I like Cocos2d-X but they don't open source their tools, and you guys have a simpler codebase, nicer Lua binding. Tools to create/manage projects are very useful. An editor with plugins MVC style would be nice. 

Doesn't beta imply 3rd party testing? :wink: :smile:

**Comment by amerkoleci** [comment]
Which QT theme do you use?

**Comment by seanpaultaylor** [comment]
The plan with the editor is that it will only be given out free and not open-source. 
It will be distributed as a binary as part of the gameplay-deps installer.
There will also be support for user plugins/addons such as docked widgets, listeners for editor events and viewport access to custom rendering tasks.

**Comment by billyquith** [comment]
So, curious as to why it won't be open sourced? This is one of the cons against Cocos2d-X. Is this part of a business plan for the gameplay3d suite?

**Comment by seanpaultaylor** [comment]
It will be free to use. There is no business plan to make any money on
this. Just avoiding fragmentation, copy-ers and all the other pitfalls of
open-source tooling.

**Comment by meiry** [comment]
Looks great ! 
can you share please on how did you embeded the engine OpenGL event loop with Qt's event loop 
Thanks!

**Comment by teamblubee** [comment]
this looks interesting but a quick question... Couldn't blender be used as an editor already and just have blender run the scripts to turn your scene into a gamplay3d binary?
