### ISSUE TITLE
Exception error with SpriteSample

### ISSUE THREAD

**Issue by hammeron-art** [gameplay3d/GamePlay#1706]
The SpriteSample in the browser project cause an exception error if you enter the example, leave and enter again.

The problem is because the 4 index (from 13 elements) in the _size member for the Font 
being draw is always like this:
_size[4] = {_format=??? _path={...} _id={...} ...} and fields with memory unable to be read. 
Whereas the other elements are:
{_format=BITMAP (0) _path="res/ui/arial.gpb" _id="arial" ...}

**Comment by seanpaultaylor** [comment]
@rcmaniac25 Can you investigate ?

**Comment by rcmaniac25** [comment]
I'd just like to mention the fix is merged.
