### ISSUE TITLE
Crash in debugAlloc()

### ISSUE THREAD

**Issue by zakki** [gameplay3d/GamePlay#1707]
My application crash only when DebugMem build, Debug build and Release build is ok.
Also AudioSample in sample-browser crash, if "streamed = true" is added to `sample.audio`.

DebugNew.cpp accesses `__memoryAllocations` without lock, so seems like it isn't thread-safe.

**Comment by seanpaultaylor** [comment]
Any fix ?

**Comment by zakki** [comment]
On windows, this works for me https://github.com/zakki/GamePlay/compare/gameplay3d:next...debugmem-thread

It's a little bit complicated, because static initialization uses `new` too.
