### ISSUE TITLE
Bluetooth support

### ISSUE THREAD

**Issue by AbdealiJK** [gameplay3d/GamePlay#1712]
I want to make a game with bluetooth communication for Android and came across gameplay3d.

I noticed it was written in C++ ... So, I guess I cannot write Native Java bluetooth communication.

So, Is there a way to send data with bluetooth ?

Also, PS : Th website gives 503 errors

**Comment by rgngl** [comment]
I don't think it's a common enough use case for the engine to support. Plus, you can always bridge code between Android Java and C++ using JNI. So using bluetooth shouldn't be an issue.
