### ISSUE TITLE
Node::findNode does not search siblings

### ISSUE THREAD

**Issue by AndreasSchacherbauerWikitude** [gameplay3d/GamePlay#1723]
I'm not quite sure if I missed something, but shouldn't Node::findNode also iterate through all siblings to find a possible match?
My problem is, that when a node(with joints) is cloned, the MeshSkin cloning is not correct when it comes to individual Joints cloning. MeshSkin::clone line 99 always receives NULL for sibling joints. This also results in a failing assertion in MeshSkin::clone line 104.

Maybe I'm missing a bigger concept behind cloning, but with my test model, changing Node::findNode to also search siblings (and return it), fixes the problem.

Any feedback is welcome, I could maybe also share a 3d model to reproduce the issue.

**Comment by seanpaultaylor** [comment]
findNode is implemented to only find within its own node hierarchy.
This would include its children and their siblings but not its own siblings.
I don't think it would make any sense if it would search outside it its own scope.

When we clone the character the node are correctly cloned. Can you link a file that is not cloned correctly ?
