### ISSUE TITLE
link error to gameplay-deps building samples in ubuntu 14

### ISSUE THREAD

**Issue by cesarpachon** [gameplay3d/GamePlay#1727]
hi, just building gameplay from fresh checkout in ubuntu (3.13.0-46-generic #76-Ubuntu SMP Thu Feb 26 18:52:49 UTC 2015 i686 athlon i686 GNU/Linux) I ran the install.sh and when running make the build process went fine. but it fails at linking-phase: 
 linking CXX executable sample-browser ld:  cannot find -lgameplay-deps

but the file is there: ~/GamePlay/external-deps/lib/linux/x86_64/libgameplay-deps.a

I think it is related to this commit: 
https://github.com/gameplay3d/GamePlay/commit/a459d335fb36a5996df34febd94a670ddf993f2f

I tested renaming the folder to x86 instead of x86_64 and now I get: 
Linking CXX executable sample-browser
/usr/bin/ld: skipping incompatible /home/cesar/Projects/GamePlay/external-deps/lib/linux/x86/libgameplay-deps.a when searching for -lgameplay-deps

how can I force the build to point with the right architecture?

**Comment by nlandry** [comment]
Hello,

I've provided a response in the [forum] (http://www.gameplay3d.org/forums/viewtopic.php?f=3&t=2273#p7708)

This isn't an issue, we don't provide x86 32-bit binaries.  To do that, you'll have to build GamePlay-deps yourself and copy the build output into external-deps into the x86 directory.

**Comment by raould** [comment]
I hit this. This is frankly utterly lame from the perspective of having people adopt the system. At the very least, the wiki should tell people up front "oh gosh we don't actually support 32 bit linux".

**Comment by raould** [comment]
p.s. doesn't help that apparently it has to be called external-deps/lib/linux/x86 instead of the usual suspects like external-deps/lib/linux/i386 or external-deps/lib/linux/i686.

i had to go searching far and wide to find the smoking gun in the link.txt files.

not so user friendly.
