### ISSUE TITLE
I'm in China, I can't download the deps.

### ISSUE THREAD

**Issue by CaptainCN** [gameplay3d/GamePlay#1730]
You know, there is a great wall in China. Someone help me.

**Comment by nbcloud** [comment]
You need climb over the GFW or use VPN.

**Comment by BruceHuang** [comment]
我可以发给你我下下来了

**Comment by CaptainCN** [comment]
你传到百度网盘哇。我来下载。

**Comment by rgngl** [comment]
You can grab the gameplay-deps repository and build it yourself.
