### ISSUE TITLE
Visual Glitches on Ubuntu 14.10

### ISSUE THREAD

**Issue by mecwerks** [gameplay3d/GamePlay#1732]
Hello I just downloaded and built the engine and I'm getting some weird glitches.

https://www.dropbox.com/sh/abrxy5mcfsz2n00/AACn3jRtZE7QNTRbRYp3mk-fa?dl=0

I'm using a MacMini (Mid 2007) running Ubuntu 14.10. One thing I noticed when I started the samples is it said my OpenGL version is -1.-1

Output of glxinfo | grep -i version
```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL version string: 2.1 Mesa 10.6.0-devel (git-94aab6c 2015-04-16 utopic-oibaf-ppa)
OpenGL shading language version string: 1.20
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 10.6.0-devel (git-94aab6c 2015-04-16 utopic-oibaf-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```

Any help would be appreciated, so far I'm really impressed with the engines capabilities.

**Comment by mecwerks** [comment]
Seems if I run the sample-browser as root then the glitches go away.

**Comment by seanpaultaylor** [comment]
Looks like an OpenGL drivers issue for your system setup.
