### ISSUE TITLE
Problems loading cameras exported from Blender

### ISSUE THREAD

**Issue by mecwerks** [gameplay3d/GamePlay#1733]
Cameras that are exported from Blender to .FBX do not work correctly. (I think the position or rotation is off somewhere, I'll look more into it tomorrow)

**Comment by seanpaultaylor** [comment]
@mecwerks Did you look into this ?

**Comment by mecwerks** [comment]
I don't remember exactly. It's been forever since i messed with it :p If i remember correctly the updated scene view script for blender worked correctly but I'm not too sure. You can look at it [here](https://github.com/mecwerks/scene-viewer).

**Comment by seanpaultaylor** [comment]
Ok. I will try it out quickly and test it out to ensure its working properly.

**Comment by havlenapetr** [comment]
camera has invalid rotation, if you call "cam->getNode()->rotateY(MATH_DEG_TO_RAD(90));" everything is fine. i think that problem could be in blender fbx exporter, if maya export works correctly.
