### ISSUE TITLE
www.gameplay3d.org is down

### ISSUE THREAD

**Issue by ppkettu** [gameplay3d/GamePlay#1736]
"Additionally, a 503 Service Temporarily Unavailable error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by egordorichev** [comment]
Why did you close issue? Server is down now!

**Comment by ppkettu** [comment]
I was confused too, when Sean Paul closed this issue, without explanation. Then I found out that the service is NOT actually down. The problem is, with the www-prefix (eg. www.gameplay3d.org) the address currently doesn't work. Maybe it still works in Canada, or for some other reason Sean Paul didn't notice this.

For now, just use gameplay3d.org (without the www.) and the services should work ok.

**Comment by egordorichev** [comment]
@ppkettu, thanks!

**Comment by ppkettu** [comment]
Posting to the forum doesn't work, it throws to the www.-side which still gives the same error. Should I file another issue?

**Comment by seanpaultaylor** [comment]
We are looking into it. Some IT guy probably updated our server again without telling us.

**Comment by jose55** [comment]
well, at this moment ....
www.gameplay3d.org
works right

**Comment by jose55** [comment]
but 
gameplay3d.org
doesn't work
and I am in London

**Comment by seanpaultaylor** [comment]
Can you verify the site is up now ?

**Comment by kwhatmough** [comment]
yes it seems to be up now

**Comment by ppkettu** [comment]
Still doesn't work from here.
Now either of them, with or without www.

**Comment by jose55** [comment]
now,  from london it doesn't work either of them.

sometimes it works others no    ?!?!?!?!?

**Comment by seanpaultaylor** [comment]
Can you verify if it is now working ? Seems to be Ok for me now.

**Comment by ppkettu** [comment]
Ok, it works!
