### ISSUE TITLE
Gameplay3D Forum not available

### ISSUE THREAD

**Issue by aaqib7** [gameplay3d/GamePlay#1744]
Forums not available anymore? Is this a bug?

**Comment by fpeschel** [comment]
I hope not. Would be nice to have it again.

**Comment by ppkettu** [comment]
I think the forums are moving to another server

**Comment by louis-mclaughlin** [comment]
Looks like they've been replaced with this https://groups.google.com/forum/#!forum/gameplay3d-developers

**Comment by seanpaultaylor** [comment]
We have lost full access to the previous forums and we will be using the Google groups and the new community.  I don't like it as much but its all I can manage.
