### ISSUE TITLE
Matrix::decompose() floating point error

### ISSUE THREAD

**Issue by zakki** [gameplay3d/GamePlay#1748]
When trace of a rotation matrix is near MATH_EPSILON, returned rotation matrix contains large scaling factor.
```C++
	Matrix matrix;
	matrix.identity();
	matrix.rotateX(TORADIANS(177));
	matrix.rotateY(TORADIANS(177));
	Quaternion quat;
	Quaternion::createFromRotationMatrix(matrix, &quat);
	Matrix m;
	m.identity();
	m.rotate(quat);
	Vector3 tx, ty, tz;
	m.transformVector(Vector3::unitX(), &tx);
	m.transformVector(Vector3::unitY(), &ty);
	m.transformVector(Vector3::unitZ(), &tz);
	printf("%f %f %f\n",  tx.length(), ty.length(), tz.length()); // 1.250615 1.250615 1.000386
```
Perhaps this threshold is too small. https://github.com/gameplay3d/GamePlay/blob/next/gameplay/src/Matrix.cpp#L520

**Comment by kwhatmough** [comment]
Thanks for raising the issue. First, let's determine the constraint error of the quaternion by inserting this:
```
    printf("error = %f\n", (quat.x * quat.x + quat.y * quat.y + quat.z * quat.z + quat.w * quat.w - 1.0f));
```
Then let's try normalizing the quaternion before using it to rotate the matrix:
```
    quat.normalize();
    ...
    m.rotate(quat);
```
A quick fix might be to insert a similar call to normalize() inside of decompose(), however I'm not sure whether this solves the real problem... Thoughts?

**Comment by kwhatmough** [comment]
Please disregard my previous comment above. I believe that you are correct: The threshold is too small.

**Comment by xthydra** [comment]
i don't know where you got the function <code>TORADIANS()</code> but, i tried to reproduce the problem,  while using <code> MATH_DEG_TO_RAD() </code> from math.h windows and i got : <code> 0.96944457292556763 0.96944457292556763 0.99995869398117065 </code>

assuming i don't know how to fix the problem, i went to get ogre engine <code> Quaternion::createFromRotationMatrix </code> which is relatively similar to our implementation of it.

so i rewrote it like that 
<code>
	float fTrace = xaxis.x + yaxis.y + zaxis.z;
	float fRoot;

	if (fTrace > 0.0)
	{
		// |w| > 1/2, may as well choose w > 1/2
		fRoot = sqrt(fTrace + 1.0f);  // 2w
		rotation->w = 0.5f*fRoot;
		fRoot = 0.5f / fRoot;  // 1/(4w)
		rotation->x = (yaxis.z - zaxis.y)*fRoot;
		rotation->y = (zaxis.x - xaxis.z)*fRoot;
		rotation->z = (xaxis.y - yaxis.x)*fRoot;
	}
</code>

with 177 i got 
<code> 1.0000001192092896 1.0000001192092896 1.0000000000000000 </code>

to be honest i'm not really sure how to debug this

**Comment by seanpaultaylor** [comment]
#define TORADIANS(degrees) (degrees * (PI / 180.0f))

I actually don't know why we even have TORADIANS or TODEGREES inside Matrix.h anyhow. They should be removed.

People should instead be using Base.h MATH_RAD_TO_DEG or MATH_DEG_TO_RAD. These have precomputed (PI over 180 and 180 over PI)

The results should be the same then and would be correct.

I think you are mixing up issues that are unrelated.

**Comment by zakki** [comment]
Some angle values causes problem. No matter how the arguments of Matrix.rotateX is generated, the float value is that value.
