### ISSUE TITLE
Video (movie playback) support

### ISSUE THREAD

**Issue by seanpaultaylor** [gameplay3d/GamePlay#176]

**Comment by ahmsayat** [comment]
Hi Sean, 
             I would like to work on this feature. It will be great enhancement to let GamePlay3D support video playback. Please assign this to me. I will use the Video class header you wrote, start implementing it on mac x86 elcapitan machine and I'll use Theora Playback Library.
-my best, Ahmed Moussa

**Comment by seanpaultaylor** [comment]
Sure. Please ensure that we will need it to be implemented on all platforms
and use existing code as a code style reference.
