### ISSUE TITLE
Terrain does not receive lighting

### ISSUE THREAD

**Issue by VinnyVicious** [gameplay3d/GamePlay#1761]
I have added a terrain object and a directional light, but the terrain is not affected by the light information.

**Comment by VinnyVicious** [comment]
Just to give some more information: i'm using a terrain loaded from RAW heightmap, described in my scene and using the default terrain shader included in the gameplay3d distribution.

**Comment by klaussilveira** [comment]
I can confirm this issue.

**Comment by xthydra** [comment]
you should check out my terrain pager/noiser/editor https://github.com/xthydra/GP_Terrain_Editor
it support point light and directional light if u use the example in "initialize" function, u just need to uncomment it out(line 250 in terraintoolmain.cpp to line 475)
