### ISSUE TITLE
Shooter example?

### ISSUE THREAD

**Issue by VinnyVicious** [gameplay3d/GamePlay#1763]
Where can we find the shooter example, showcased in the website?

**Comment by dgough** [comment]
We never submitted that sample to github because we bought those models and textures so we couldn't release them.

The code uses [Recast & Detour](https://github.com/memononen/recastnavigation) for pathfinding. The rest of the code doesn't compile because it was written for an older version of gameplay3d.

**Comment by HardlineStudios** [comment]
I think it'd still be nice to see just the code and how you guys implemented various things. Would be a good learning experience!

**Comment by VinnyVicious** [comment]
Well, i know where those assets are from. The license allows the data to be distributed in binary-mode, so, if you guys distribute the demo with the gbp files, it's OK. 

Or, just release the code, which is the important part. Assets can be replaced with boxes and capsules. :D

**Comment by HardlineStudios** [comment]
LOL replaced with box and capsules, it may become the next big hit game! :P

**Comment by VinnyVicious** [comment]
Seeing the integration with Recast/Detour would be amazing. And the enemy ai and bullet detection as well.

**Comment by VinnyVicious** [comment]
Any news on releasing this?

**Comment by xthydra** [comment]
wait so, cast n detour isn't built on top of bullet engine? redundant

**Comment by seanpaultaylor** [comment]
Recast and detour use completely different technology and are used for different usage. There is no redundance.

**Comment by dgough** [comment]
I couldn't find the whole sample. All I could find was the simple (unoptimized) wrapper I created around the detour API. 

Keep in mind that this code is 3 years old. It likely won't compile if the API has changed. 

Detour has a tool that lets you export a nav mesh as a binary file. The code below can read that binary file using NavMesh::load(const char* path).

[NavMesh.h.txt](https://github.com/gameplay3d/GamePlay/files/8614/NavMesh.h.txt)
[NavMesh.cpp.txt](https://github.com/gameplay3d/GamePlay/files/8615/NavMesh.cpp.txt)
