### ISSUE TITLE
Parallax mapping

### ISSUE THREAD

**Issue by VinnyVicious** [gameplay3d/GamePlay#1764]
Has anyone managed to get parallax mapping working with the engine?

**Comment by louis-mclaughlin** [comment]
This isn't an issue, ask questions about gameplay here:

https://groups.google.com/forum/#!forum/gameplay3d-developers

**Comment by VinnyVicious** [comment]
There's nothing there. The forums were deleted.

**Comment by louis-mclaughlin** [comment]
![image](https://cloud.githubusercontent.com/assets/6073390/8627402/c1a937ee-2742-11e5-95b4-f5bf006627f9.png)
