### ISSUE TITLE
Particle Emitter Rendering Artifacts

### ISSUE THREAD

**Issue by HardlineStudios** [gameplay3d/GamePlay#1774]
In **ParticleEmitter.cpp** line 121, the emitter does this:

```C++
int spriteFrameRandomOffset = sprite->getInt("frameRandomOffset");
```

BUT if there are less frames than what ```spriteFrameRandomOffset``` is set to, the emitter will sometimes pick a random frame outside the valid range and thus lead to empty quads being rendering with no textures which of course won't look right.

This can be fixed be replacing by clamping ```spriteFrameRandomOffset```:

```C++
int spriteFrameRandomOffset = min(sprite->getInt("frameRandomOffset"), spriteFrameCount);
```

My GP source base is still 3.0.0 and heavily merged with my existing engine so it wasn't very trivial to update just that file to the next branch.

**Comment by seanpaultaylor** [comment]
Fixed in 'next' branch.
