### ISSUE TITLE
Clicking Image in "Particles" Crashes via Segfault

### ISSUE THREAD

**Issue by qubodup** [gameplay3d/GamePlay#1776]
On Arch Linux 64bit, If I click the "Image" image in the particles sample (./sample-browser), it crashes:
<pre>Program received signal SIGSEGV, Segmentation fault.
0x00007ffff17265f6 in ?? () from /usr/lib/libpng16.so.16
(gdb) bt
#0  0x00007ffff17265f6 in ?? () from /usr/lib/libpng16.so.16
#1  0x00007ffff1733729 in ?? () from /usr/lib/libpng16.so.16
#2  0x00007ffff1736589 in ?? () from /usr/lib/libpng16.so.16
#3  0x00007ffff1727814 in ?? () from /usr/lib/libpng16.so.16
#4  0x00007ffff172843b in png_process_data ()
   from /usr/lib/libpng16.so.16
#5  0x00007ffff4631659 in ?? () from /usr/lib/libgdk_pixbuf-2.0.so.0
#6  0x00007ffff4625d45 in ?? () from /usr/lib/libgdk_pixbuf-2.0.so.0
#7  0x00007ffff46265ed in gdk_pixbuf_loader_close ()
   from /usr/lib/libgdk_pixbuf-2.0.so.0
#8  0x00007ffff462228b in ?? () from /usr/lib/libgdk_pixbuf-2.0.so.0
#9  0x00007ffff46241ac in gdk_pixbuf_new_from_stream ()
   from /usr/lib/libgdk_pixbuf-2.0.so.0
#10 0x00007ffff69b0084 in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#11 0x00007ffff69b30aa in gtk_icon_info_load_icon ()
   from /usr/lib/libgtk-x11-2.0.so.0
#12 0x00007ffff69b3217 in gtk_icon_theme_load_icon ()
   from /usr/lib/libgtk-x11-2.0.so.0
#13 0x00007ffff69aea96 in gtk_icon_set_render_icon ()
   from /usr/lib/libgtk-x11-2.0.so.0
#14 0x00007ffff6afe7dd in gtk_widget_render_icon ()
   from /usr/lib/libgtk-x11-2.0.so.0
#15 0x00007ffff6991fbe in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#16 0x00007ffff6365651 in ?? () from /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff636725d in g_object_newv ()
   from /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff63679f4 in g_object_new ()
   from /usr/lib/libgobject-2.0.so.0
#19 0x00007ffff6997954 in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#20 0x00007ffff6365651 in ?? () from /usr/lib/libgobject-2.0.so.0
#21 0x00007ffff636725d in g_object_newv ()
   from /usr/lib/libgobject-2.0.so.0
#22 0x00007ffff63679f4 in g_object_new ()
   from /usr/lib/libgobject-2.0.so.0
#23 0x00007ffff6993511 in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#24 0x00007ffff6365651 in ?? () from /usr/lib/libgobject-2.0.so.0
#25 0x00007ffff63676a5 in g_object_new_valist ()
   from /usr/lib/libgobject-2.0.so.0
#26 0x00007ffff63679e1 in g_object_new ()
   from /usr/lib/libgobject-2.0.so.0
#27 0x00007ffff699397d in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#28 0x00007ffff6993a8a in gtk_file_chooser_dialog_new ()
   from /usr/lib/libgtk-x11-2.0.so.0
#29 0x0000000000726c45 in gameplay::Platform::displayFileDialog(unsigned long, char const*, char const*, char const*, char const*) ()
#30 0x00000000006c03c0 in gameplay::FileSystem::displayFileDialog(unsigned long, char const*, char const*, char const*, char const*) ()
#31 0x000000000066a82e in ParticlesSample::updateTexture() ()
#32 0x000000000066872a in ParticlesSample::controlEvent(gameplay::Control*, gameplay::Control::Listener::EventType) ()
#33 0x00000000006ab1c4 in gameplay::Control::notifyListeners(gameplay::Control::Listener::EventType) ()
#34 0x00000000006cd8ff in gameplay::Form::handlePointerPressRelease(int*, int*, bool, unsigned int) ()
#35 0x00000000006cdc0d in gameplay::Form::pointerEventInternal(bool, int, int, int, int) ()
#36 0x00000000006ce025 in gameplay::Form::mouseEventInternal(gameplay::Mouse::MouseEvent, int, int, int) ()
#37 0x0000000000723381 in gameplay::Platform::mouseEventInternal(gameplay::Mouse::MouseEvent, int, int, int) ()
#38 0x0000000000725f3a in gameplay::Platform::enterMessagePump() ()
#39 0x00000000006da186 in main ()</pre>

**Comment by rgngl** [comment]
This looks like it's crashing deep inside GTK. I think it might be related to this: https://groups.google.com/forum/#!topic/wx-dev/pjQ4YOt_J9M

**Comment by seanpaultaylor** [comment]
It doesn't seem to be crashing on Ubuntu. Can anyone confirm if its crashing on other Linux Disto's too ?
