### ISSUE TITLE
Sharing of material does not work

### ISSUE THREAD

**Issue by buggins** [gameplay3d/GamePlay#1777]
I'm trying to reuse model and material in several scene nodes.
Only one (recent added) node is drawn unless separate copy of model and material is created.
Expected behavior: it's possible to add the same Model instance to several nodes.
Observable behavior: when model is used in several nodes, only one of nodes is drawn. Moreover, I cannot even reuse Material in to separate instances of models.

Sample is based on default project. 

Platform: Windows.

Following code is working:

	// Create the material for the cube model and assign it to the first mesh part.
	Material * material = createMaterial();
	material->getParameter("u_directionalLightColor[0]")->setValue(lightNode->getLight()->getColor());
	material->getParameter("u_directionalLightDirection[0]")->bindValue(lightNode, &Node::getForwardVectorWorld);

	// Create the cube mesh and model.
	Mesh* cubeMesh = createCubeMesh();
	Model* cubeModel = Model::create(cubeMesh);
	// Release the mesh because the model now holds a reference to it.
	SAFE_RELEASE(cubeMesh);

	_group1 = _scene->addNode("group1");

	_cubeNode = Node::create("cube"); // _scene->addNode("cube");
	_group1->addChild(_cubeNode);
	//SAFE_RELEASE(_cubeNode);
	//_cubeNode = _scene->addNode("cube");
	_cubeNode->setDrawable(cubeModel);
	_cubeNode->rotateY(MATH_PIOVER4);
	cubeModel->setMaterial(material);

	// Create the material for the cube model and assign it to the first mesh part.
	Material * material2 = createMaterial();
	//SAFE_RELEASE(material);
	material2->getParameter("u_directionalLightColor[0]")->setValue(lightNode->getLight()->getColor());
	material2->getParameter("u_directionalLightDirection[0]")->bindValue(lightNode, &Node::getForwardVectorWorld);

	Mesh* cubeMesh2 = createCubeMesh();
	Model* cubeModel2 = Model::create(cubeMesh2);
	//SAFE_RELEASE(cubeMesh2);
	_cubeNode2 = Node::create("cube2");
	_group1->addChild(_cubeNode2);
	_cubeNode2->setDrawable(cubeModel2);
	cubeModel2->setMaterial(material2);
	_cubeNode2->rotateY(MATH_PIOVER4 / 2);
	_cubeNode2->scaleX(0.5f);
	_cubeNode2->translateZ(0.5f);

Following code is NOT working (node2 reusing same instance of material as node1 - only node2 is drawn):

	// Create the material for the cube model and assign it to the first mesh part.
	Material * material = createMaterial();
	material->getParameter("u_directionalLightColor[0]")->setValue(lightNode->getLight()->getColor());
	material->getParameter("u_directionalLightDirection[0]")->bindValue(lightNode, &Node::getForwardVectorWorld);

	// Create the cube mesh and model.
	Mesh* cubeMesh = createCubeMesh();
	Model* cubeModel = Model::create(cubeMesh);
	// Release the mesh because the model now holds a reference to it.
	SAFE_RELEASE(cubeMesh);

	_group1 = _scene->addNode("group1");

	_cubeNode = Node::create("cube"); // _scene->addNode("cube");
	_group1->addChild(_cubeNode);
	_cubeNode->setDrawable(cubeModel);
	_cubeNode->rotateY(MATH_PIOVER4);
	cubeModel->setMaterial(material);

	// Create the material for the cube model and assign it to the first mesh part.
	//Material * material2 = createMaterial();
	//material2->getParameter("u_directionalLightColor[0]")->setValue(lightNode->getLight()->getColor());
	//material2->getParameter("u_directionalLightDirection[0]")->bindValue(lightNode, &Node::getForwardVectorWorld);

	Mesh* cubeMesh2 = createCubeMesh();
	Model* cubeModel2 = Model::create(cubeMesh2);
	SAFE_RELEASE(cubeMesh2);
	_cubeNode2 = Node::create("cube2");
	_group1->addChild(_cubeNode2);
	_cubeNode2->setDrawable(cubeModel2);
	cubeModel2->setMaterial(material); // reuse material
	_cubeNode2->rotateY(MATH_PIOVER4 / 2);
	_cubeNode2->scaleX(0.5f);
	_cubeNode2->translateZ(0.5f);

**Comment by HardlineStudios** [comment]
I went through this too but it's not actually a bug! The static components of the material like the textures and shaders are re-used internally during material creation if they were previously created BUT the dynamic components like the shader uniforms are unique to the instance hence why each create model should have it's own material unless it's a completely static material in which case you should be able to share.

**Comment by buggins** [comment]
Ok.
At least sharing of Mesh is working.

**Comment by rgngl** [comment]
In addition, the Effect class that wraps the actual GLSL shaders is also shared. Effect::create() won't create a new Effect instance if it has already created one with the same parameters(vertex shader, fragment shader and defines). So the overhead of the Material is only for per object stuff.
