### ISSUE TITLE
Game::exit() Bug

### ISSUE THREAD

**Issue by terrygrylls** [gameplay3d/GamePlay#1779]
GamePlay / gameplay / src / Game.cpp
Line 332
void Game::exit()

The Game::exit function has been changed to use exit(0) to delegate the cleanup of 
dynamic memory to the operating system. This is an incorrect assumption as most 
applications need to do an orderly shutdown to perform other tasks such as writing files 
like settings, high scores, and performing network requests etc.

Game::exit() should call Game::shutdown() which calls Game::finalize() for this very purpose.

If a quick exit is preferred then we should do what c++ 11 does, and provide a quick exit function,
which a user calls to set a flag, so when an exit occurs it can choose between an orderly
and a quick exit. Thus allowing the programmer to control the method of exit.

Because the current shutdown code is only called when testing for memory leaks the shutdown
code has become isolated and will not be updated/tested and will slowly wither and die. 

This already can be seen in platform-windows.cpp were WM_DESTROY calls exit(0) instead of 
Game::exit() or Game::shutdown().

Anyone upgrading from 2.0 to 3.0 Game:finalize() is no longer called, which is a serious oversight as most people wont realize this functionality has been changed.

**Comment by xthydra** [comment]
is that why when u would close a gameplay application with "alt+f4" it would output a fatal exception?

**Comment by seanpaultaylor** [comment]
I think we should fix this. We need to fix it as though to still be calling users finalize() method.

**Comment by xthydra** [comment]
on windows 10, the game engine throw a fatal exception when you close an application in release mode (including samples) that was open from MSVS 2015.
It doesn't throw an exception if you start the application without MSVS 2015.
it doesn't throw an exception if you close the application in debug mode from MSVS 2015.
it can be a bug inside MSVS 2015 but i can't confirm the bug unless i would be able to debug microsoft visual studio 2015 lol.
