### ISSUE TITLE
gameplay-encoder is not working on OSX with fbx 2016.1

### ISSUE THREAD

**Issue by darting** [gameplay3d/GamePlay#1780]
I got the following info then it stuck in there.

```
Loading FBX file.
Do you want to group animations? (y/n)
y
Loading Scene.
Triangulate.
Load nodes.
Load materials
Loading animations.
```

The model file (Hyperspace_Madness_Sven.fbx) I downloaded from the following link:
http://areadownloads.autodesk.com/oc/hosting/hyperspace_madness_fbx_review_samples.zip

Where I can check the log?

thanks

**Comment by xthydra** [comment]
i tried to debug the encoder while loading the model you pointed out.
 there's an animation that required 10 million frames to iterated trough.
not all animations inside that FBX file required that huge amount of frames to process per animation.
so i'm assuming it has something to do with how the file was saved

**Comment by seanpaultaylor** [comment]
We probably need to update the system to use the newer version then.

**Comment by seanpaultaylor** [comment]
I just rebuilt with FBX 2016.1.2 using the update VS 2015. This seems to be an problem with that FBX file. I would just what is exactly being exports. A dozen other files that I tried with and without animations all encoded and loaded successfully.
