### ISSUE TITLE
Node::findNode infinite loop cause it's searching in Mesh Skin

### ISSUE THREAD

**Issue by Hamsho** [gameplay3d/GamePlay#1781]
Hello,
I encountered a curious issue in Node::findNode(const char* id, bool recursive, bool exactMatch) const function, it enters a infinite loop without finding the needed node. 
When debugging i found out that each time it reaches a node with mesh skin, it will start from the root node of the mesh skin which incidentally is our starting node of the first search! Maybe a visited tag on the node can fix the problem?

I can send you the mesh for testing if needed

Ahmad

**Comment by lonnieg1214** [comment]
I am new to contributing to open source but I would love the challenge and experience of helping out. Can I help with this issue? I agree that a tag should help but where can I go to read the source code to make sure?

**Comment by Hamsho** [comment]
Hey, 
Sorry for the late replay and thanks for trying to help,
What i'm trying to do is quite simple, loading and rendering this model:
https://dl.dropboxusercontent.com/u/59513804/Octa.fbx using the bundle and findNode functions but i can't seem to be able to do that.

The function in question is in Node.cpp, Node* Node::findNode(const char* id, bool recursive, bool exactMatch) const, when we check if the drawable has a mesh skin, this will make the findnode restart its search from the root node ==> infinite loop.

**Comment by seanpaultaylor** [comment]
Looks like a bug. Let me know if you can fix it ?

**Comment by seanpaultaylor** [comment]
@lonnieg1214 Do you plan to work on this ? If so let me know and I can assign it to you.

**Comment by CSDragon** [comment]
I'm in the same boat as lonnieg1214. Interested in getting my hands wet on Github. Since it's been 2 months, since they said they would, I'll take a stab at it.

**Comment by CSDragon** [comment]
Ok, so if it's even getting to the recursive part in the first place, but is never returning null,

````
// Recurse.
    if (recursive)
    {
        for (Node* child = getFirstChild(); child != NULL; child = child->getNextSibling())
        {
            Node* match = child->findNode(id, true, exactMatch);
            if (match)
            {
                return match;
            }
        }
    }
````

in here, somewhere lies the issue.

For clarification, does it ever LEAVE the root node?

If it does, then there's a problem in the child hierarchy where a child has decided one of its children is one of its parents.

If it doesn't, the problem must be that the node believes it is its own root node.

**Comment by CSDragon** [comment]
Alternitively, this could be causing the issue

````
Node* match = rootNode->findNode(id, true, exactMatch);
            if (match)
            {
                return match;
            }
````

As as far as I can tell, there's no check to see if this==rootNode, which would cause an infinite loop.

**Comment by benloong** [comment]
```cpp
        if (model->getSkin() != NULL && (rootNode = model->getSkin()->_rootNode) != NULL)
        {
            if ((exactMatch && rootNode->_id == id) || (!exactMatch && rootNode->_id.find(id) == 0))
                return rootNode;

            Node* match = rootNode->findNode(id, true, exactMatch);
            if (match)
            {
                return match;
            }
        }
``` 
```(rootNode = model->getSkin()->_rootNode)```  may lead searching rewind to beginning
