### ISSUE TITLE
textured shaders with no texture behavior

### ISSUE THREAD

**Issue by xthydra** [gameplay3d/GamePlay#1783]
i created a model with no textures or colored vertexes and i applied the default textured shaders on it.

the model somehow managed to grab the first texture of my terrains and apply it to the model.

i'm not the type of guy that's really smart in term of acknowledging what's conventional or not but i'm assuming it's not supposed to auto-magically find a texture and apply it to a model with no texture.

i think the correct way to prevent the current type of behavior would be to have an encoded PNG texture as a file inside the engine library that would be applied to a model with textured shaders and no texture

**Comment by seanpaultaylor** [comment]
I agree. This is probably just a bug. I think it might be best that we have a better 'unset' defaul texture of a shaded version of pink. That way it stands out too.

**Comment by xthydra** [comment]
is that the texture you had in mind?
![blank](https://cloud.githubusercontent.com/assets/3760205/10864042/d5618710-7fb6-11e5-8043-f62c84b02d95.png)

**Comment by seanpaultaylor** [comment]
Sure. That would be fine. I think we want the default material to also have shading from a constant directional light source so we can also more easily see the geometry/shape.

**Comment by xthydra** [comment]
i'm not really sure what you are asking by a "shading from a constant directional light source".
because from what i assume, is that i would need to create a default light source when the platform is initialized and then call it from material.cpp because that's where the textured shader is created and it doesn't seem like there's a simple way for me to be able to do that unless there's a rather more simple way for me to lite up a texture permanently without any light source.

**Comment by seanpaultaylor** [comment]
You don't need an actual light to make the lighting work in a material. Just pass the defines and parameters to the material. We don't want any extra default lights kicking around in the platform for no reason at all. We just want to pass the default material alll the parameters needed. This is easy. 
The other challenge about default shaders and why I would not use a texture but rather a color (pink): Not all mesh will include UV's in their vertex input layout. Typically the bare minimum that most geometry has is positions and normals. The default material used for unset materials should basically do some basic check on the mesh vertex format and if there are normals, then you can pass the lighting defines and the light params. If not we can still just set it to pink. However, only color will be noticed and no shading from any light source.

**Comment by xthydra** [comment]
i've put textured shaders with a diffuse texture parameter pointing out to the texture i've shown you on the mesh batch example and it automatically become somewhat pink, so i'm assuming i don't really need to check if a mesh have UV's.
on other hand my model which i think have normals and no light on do look very dark , so i think i would need to put a virtual light or someshit
