### ISSUE TITLE
Changing Android build system to Gradle/Android Studio

### ISSUE THREAD

**Issue by hammeron-art** [gameplay3d/GamePlay#1786]
When building for Android all the compilation and apk installation works fine without errors but the app crash on startup (Android 4.4.4).
The current pipeline makes it kinda hard to debug and customize the build.
Moving to Gradle build system and Android Studio (as Google itself) will allow a better general workflow with formated logging, debugging, analysis and build customization.

**Comment by seanpaultaylor** [comment]
I agree. I would like to change the Android build pipeline to use gradle and also have projects setup for Android Studio.

**Comment by HardlineStudios** [comment]
I've been using nVidia's AndroidWorks with Visual Studio 2013 Community Edition and it works great for building an debugging Android related stuff. I found Android Studio to be WAY to heavy and not nearly as good for native stuff however that was a few versions ago so not sure if it's gotten better.

https://developer.nvidia.com/content/introducing-androidworks

**Comment by seanpaultaylor** [comment]
Ok. Good to know. Perhaps we should just setup instructions on how to do that. 
BTW. Does it work with Visual Studio 2015 Community. We may be upgrading to that soon.

**Comment by HardlineStudios** [comment]
Or create the project/solution files and include them in the tree like you did with the x86 version?

I'm going to highly assume it works with VS 2015 Community.

**Comment by hammeron-art** [comment]
Android Studio started support to native sdk in the 1.3 version. Now in 1.5 it works great but you know... is still experimental. Java IDEs are always heavy to me but in my current my pc I no longer see slowdowns.
I didn't know about AndroidWorks. I also would use it instead of Android Studio.

**Comment by seanpaultaylor** [comment]
We can look at this at a later time.
