### ISSUE TITLE
Resource chache behavior

### ISSUE THREAD

**Issue by hammeron-art** [gameplay3d/GamePlay#1788]
Looking around the resource classes I noticed there is some of them (like fonts) that have caches working fine but others (like bundles) has a cache vector but is not filled when the resource is loaded or don't have cache at all.
Calling Scene::load("res/main.scene") two times for example will create two copies of the same bundle but Font::create("res/ui/arial.gpb") two times will return the same font.
Is this behavior by design?

**Comment by xthydra** [comment]
what "cache vector" is not filled? i can't seem to understand the behavior your are trying to describe here.
can you point a line in the engine that would relatively define the "cache vector" of a scene?

**Comment by hammeron-art** [comment]
The Bundle class has a __bundleCache vector (Bundle.cpp) but no value is pushed to it. When you load a file, this cache is checked but the bundle is never pushed to the cache. In other words, if you load the same file you will get a copy instead of the pointer to the first one.
On the other hand, Font class always push the loaded font on its cache and return just the pointer.
AudioSource don't have a cache at all.
The file management is inconsistent in this regard.

**Comment by xthydra** [comment]
is that what itching you Bundle::create("scene.gpb") , Scene::load("scene.gpb") ?
are you implying that you want to merge Bundle class and Scene class together?

**Comment by HardlineStudios** [comment]
Yeah I noticed this too, materials, textures and fonts all seem to have their own cache to prevent stuff from being loaded twice but the bundle cache doesn't seem to be used. 

I would sooner do away with having each object do their own cache and delegate it instead to a central resource manager that could potentially load things in a separate thread.
