### ISSUE TITLE
Keyframe interpolation example?

### ISSUE THREAD

**Issue by VinnyVicious** [gameplay3d/GamePlay#1789]
I'm trying to implement something along the lines of Overgrowth's techniques: http://www.gamasutra.com/view/news/216973/Video_An_indie_approach_to_procedural_animation.php

Blending between only two keyframes at a specific time, producing a realtime animation. Also, does anyone know any IK examples for gameplay3d?

**Comment by seanpaultaylor** [comment]
Sorry no I don't. 
In the future can you please not create a issue to ask a question. 
Please use the community group for this instead. Thanks.
