### ISSUE TITLE
Visual Studio 2015 support

### ISSUE THREAD

**Issue by seanpaultaylor** [gameplay3d/GamePlay#1791]
This will be update in next branch soon.

**Comment by terry8yu** [comment]
Does it support to use VS2015 to build Android apps?

**Comment by HardlineStudios** [comment]
I use this and it's amazing. Allows you to compile and deploy to any Android device, you can do line-by-line debugging, watch variables etc. Includes extra features for the Tegra chipset like profiling GPU performance.

https://developer.nvidia.com/codeworks-android

You can also get the Adreno and PVR SDK which offer similar profiling tools for those chipsets as well.

**Comment by seanpaultaylor** [comment]
Not yet. But I will work on it.

**Comment by seanpaultaylor** [comment]
Android support for VS 2015 will be tracked as a separate issue later. This is now in master and next branches.
