### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by seanpaultaylor** [gameplay3d/GamePlay#1796]
Apple tvOS Support

**Comment by yuangu** [comment]
what about winphone8.1 or win10.Maybe can ported by Angle .Here is this project url :https://github.com/MSOpenTech/angle

**Comment by rcmaniac25** [comment]
Angle is known already, but it takes a good performance hit as of the last test of it. https://github.com/gameplay3d/GamePlay/issues/556
