### ISSUE TITLE
Issue with animations from Blender

### ISSUE THREAD

**Issue by hammeron-art** [gameplay3d/GamePlay#1798]
Does anyone have a clue of why animations from Blender don't work?
The encoder seems to pick the animation data but it don't work in gameplay (also it seems to create many animations despite the option to group them).
I know the concept of skinning, channels and stuff but the code for the animation system is kinda hard to grasp and debug. Also there is no info about material setup for this.

Btw, I was using the Open Asset Import Library to encoder others formats in GPB for a side project of mine.
The data generated by Assimp is much more lean than the FBX SDK but all the important things are there.
What do you think about replacing the fbx sdk (with all its licence issues and closed source stuff) by Assimp?

**Comment by xthydra** [comment]
i do agree that exporting animations from blender is hard even though i didn't understand why sometime it work and sometime it didn't work.
i remember that someone made a scene viewer for blender and it's using gameplay engine to preview the scene and animations.
https://github.com/rlofc/scene-viewer
i am able to preview an animation using gameplay next branch and FBX SDK 2015.
I'm kind of curious what you've made that would be encoding 3D models into .GPB format by using assimp.
If we would be able to import .bvh animation format and apply bones weight on a 3D model during runtime....well shit

**Comment by hammeron-art** [comment]
I never got an animation from Blender to work...
I tried this scene viewer but doesn't work too.

I just implemented another scene loader class for the gameplay-encoder using assimp (so far with node hierarchy and base mesh encoding).
It was easier than I thought.
Collada, FBX, 3ds and even .blend formats seem to be working fine.

**Comment by xthydra** [comment]
It wouldn't be a wise choice to replace FBX SDK encoder by assimp encoder unless everyone stop maintaining the FBX SDK encoder.
I personally prefer if you would push your encoder in next branch, keep both encoders until people lose interest in the FBX SDK encoder and stop maintaining it.
I guess sean would only accept such change if you would imply that you are going to review every pull requests affecting the assimp encoder.

**Comment by hammeron-art** [comment]
Well, there are no significant changes to the code of the fbx encoder in 3 years.

My branch also have changes to the way resources are loaded to support proper caching and reloading (useful for level editor was you can use a system of file watcher and reload changed assets on the fly). My issue about the resource cache gets closed without reply and I'll not revert it so I can't push my changes.

**Comment by xthydra** [comment]
sean mentioned that he's pretty busy with the creation of the QT editor and i don't think that you should feel offended because he didn't discuss the issue yet.

**Comment by hammeron-art** [comment]
I'm not offended. I just implement animations with Assimp and I'm separating the code to be able to release it as extensions https://github.com/hammeron-art/gp-extensions. This way others can use, integrate in the official framework if sounds good and I can keep pushing my fixes for the framework.
