### ISSUE TITLE
In windows using VS2015 creating new project the toolset is VisualStudio 2013

### ISSUE THREAD

**Issue by meiry** [gameplay3d/GamePlay#1807]
Using the newproject.bat script 
Need to change to VisualStudio 2015 (v140)

**Comment by wq5070367** [comment]
there u go
----- 原始邮件 -----
发件人：Meir Yanovich <notifications@github.com>
收件人：gameplay3d/GamePlay <GamePlay@noreply.github.com>
主题：[GamePlay] In windows using VS2015 creating new project the toolset is VisualStudio 2013 (#1807)
日期：2015年12月26日 21点09分

Using the newproject.bat script 

Need to change to VisualStudio 2015 (v140)

&mdash;

**Comment by seanpaultaylor** [comment]
Do you have a pull request ?
