### ISSUE TITLE
error when I exit the racer sample

### ISSUE THREAD

**Issue by chinaliye** [gameplay3d/GamePlay#1813]
I'm using windows and visual studio 2015.I build the gameplay framework successfully and I can run all the samples(sample browser,character,racer and spaceship).But sometimes an error will appear when I quit the racer sample.Can anyone tell me why?Maybe it's a bug.
![sa](https://cloud.githubusercontent.com/assets/16770928/12410170/0988d3e2-bead-11e5-8693-bf750898f54a.png)

**Comment by louis-mclaughlin** [comment]
What's the callstack?

**Comment by xthydra** [comment]
are you debugging the application built in release mode?

**Comment by chinaliye** [comment]
the callstack is as following...
![e_ y6 yeupzcf t txg](https://cloud.githubusercontent.com/assets/16770928/12449809/cfac6de6-bfba-11e5-8e13-fc7530e81c9c.png)

**Comment by chinaliye** [comment]
It's built in the debug mode.
![mrar mkcj 1xz8um1z o](https://cloud.githubusercontent.com/assets/16770928/12449890/393af930-bfbb-11e5-9f3a-ce6ec9b55e0f.png)

**Comment by chinaliye** [comment]
It is worth mentioning that this error occurs just sometimes,not always.It is really strange.

**Comment by fredakilla** [comment]
seems to be a openal error, check in your console the last lines, it should be the returned error code.

/** No error. */
#define AL_NO_ERROR                              0

/** Invalid name paramater passed to AL call. */
#define AL_INVALID_NAME                          0xA001

/** Invalid enum parameter passed to AL call. */
#define AL_INVALID_ENUM                          0xA002

/** Invalid value parameter passed to AL call. */
#define AL_INVALID_VALUE                         0xA003

/** Illegal AL call. */
#define AL_INVALID_OPERATION                     0xA004

/** Not enough memory. */
#define AL_OUT_OF_MEMORY                         0xA005
