### ISSUE TITLE
active

### ISSUE THREAD

**Issue by teamblubee** [gameplay3d/GamePlay#1814]
is this project being actively developed? I see recent issue comments and updates about 3 months ago.

**Comment by benloong** [comment]
active 11 days ago

**Comment by seanpaultaylor** [comment]
I am working on a major overhaul of the framework/engine. However, now a day, I only get a 4 hours a weeks to really work on the project on the train and weekends.
Unfortunately the original core developers have but mostly all moved on to new projects, etc.
Until I get more interested developers the engine will have mostly bug fixes.
