### ISSUE TITLE
android build error in next: Mesh.h:55:25: error: 'GL_READ_ONLY' was not declared in this scope

### ISSUE THREAD

**Issue by louis-mclaughlin** [gameplay3d/GamePlay#1825]
[armeabi-v7a] Compile++ arm  : gameplay <= AbsoluteLayout.cpp
In file included from jni/../../src/SpriteBatch.h:6:0,
                 from jni/../../src/Font.h:4,
                 from jni/../../src/Theme.h:6,
                 from jni/../../src/Control.h:7,
                 from jni/../../src/AbsoluteLayout.cpp:2:
jni/../../src/Mesh.h:55:25: error: 'GL_READ_ONLY' was not declared in this scope
         MAP_READ_ONLY = GL_READ_ONLY,
                         ^
jni/../../src/Mesh.h:56:26: error: 'GL_WRITE_ONLY' was not declared in this scope
         MAP_WRITE_ONLY = GL_WRITE_ONLY,
                          ^
jni/../../src/Mesh.h:57:26: error: 'GL_READ_WRITE' was not declared in this scope
         MAP_READ_WRITE = GL_READ_WRITE
                          ^
make: *** [obj/local/armeabi-v7a/objs/gameplay/AbsoluteLayout.o] Error 1

**Comment by seanpaultaylor** [comment]
Are you sure you have the correct NDK ?

**Comment by seanpaultaylor** [comment]
I see. The Android NDK needs to use these as extensions. I will need to fix this.

**Comment by seanpaultaylor** [comment]
Fixed in next.
