### ISSUE TITLE
Unable to load and add new gpb into a scene ? 

### ISSUE THREAD

**Issue by deep4U** [gameplay3d/GamePlay#1832]
After converting my fbx 3d model to gpb using the gameplay-encoder I wanted to add this gpb in a scene through code. But to my surprise we can only load it as another scene and can not add this object to current scene. Let me know if there is a way though. Tried reading the api and classes but unable to find a way to do this.
what I need to do ultimately is export a object from blender / maya with materials and textures(as fbx than encode to gpb) and add into scene of my game code as a new node added to the scene.
Note: the scene itself is from another gpb.(I am using sample.gpb from browser code as scene and want to add new node and load mesh and material from another gpb into that node).

**Comment by dgough** [comment]
Instead of using `Bundle::loadScene()`, you can use `Bundle::loadNode()` or `Bundle::loadMesh()` and then add the node or mesh to an existing scene.

https://github.com/gameplay3d/GamePlay/blob/master/gameplay/src/Bundle.h#L58

**Comment by deep4U** [comment]
ok will try this also will the materials and texture mappings from fbx also be included in the encoded gpb node?

**Comment by deep4U** [comment]
hi
as you suggested I used code as below
Bundle* bundle = Bundle::create("res/railstation.gpb");
//Node* node = bundle->loadNode("railstation");
//_scene->addNode(node);
Node* node = bundle->loadNode("home001");
_scene->addNode(node);
Mesh* meshnode = bundle->loadMesh("home001_Mesh");
Model* model = model->create(meshnode);
//Node node1("homemesh");
Node* node1=gameplay::Node::create("homemesh");
node1->setDrawable((Drawable*)model);
node->setDrawable((Drawable*)model);
//_scene->addNode(node)
_scene->addNode(node);
_scene->addNode(node1);



loaded the mesh and added to both nodes still not showing anything

I listed to nodes contained by my gpb which is encoded from the fbx 
they are as below
 4
__Animations__
__SCENE__
home001
home001_Mesh
so  I thought mesh is Mesh drawable and home001 is a normal node
tried adding home001 directly also still does not work

**Comment by deep4U** [comment]
update tried adding this too
node->setEnabled(true);
node1->setEnabled(true);
model->draw(false);
still does not work 
shall I attach fbx and gpb files or still problem is in the way I am loading it in code?

**Comment by xthydra** [comment]
from what i understand when exporting FBX files from blender, it's only going to save the 3D model and the UV texture coordinates and so i believe when you are going to load the .gpb you would need to assign a material to it either via programming or with a .scene

the character sample assign the material with https://github.com/gameplay3d/GamePlay/blob/master/samples/character/res/common/sample.scene
and the material assign texture with https://github.com/gameplay3d/GamePlay/blob/master/samples/character/res/common/sample.material

**Comment by deep4U** [comment]
and If I need only texture than ? will it search for the images and load textures automatically?

**Comment by xthydra** [comment]
i don't think so no.
but if you want a sample on how to create a material inside the application i used to manually create material for trees in my terrain editor

https://github.com/xthydra/GP_Terrain_Editor/commit/1a48ec5490d8893a1ac00ff3c652fa3f74f53ac7#diff-6f704dfdb1181e64de7444a1ccd2a276

**Comment by deep4U** [comment]
But most of engines out there would apply the textures automatically why this feature is still not added in the engine at this stage ?
Most engines will search for the image file mentioned in the object file and attach it if found applying all textures to all subobjects automatically.

**Comment by deep4U** [comment]
or is there any other way to export a object which has multiple subobjects and textures mapped to them from blender to gameplay engine without needing to manually assign each texture to specific subobject /object ?and load that object in a scene?

**Comment by xthydra** [comment]
i mean, i might be wrong but when i look at 
https://github.com/gameplay3d/GamePlay/blob/master/tools/encoder/src/FBXSceneEncoder.cpp#L102
 i do think the encoder can output the material but i just dont know how.

**Comment by deep4U** [comment]
That would be great if someone here knows how to get it.
Ok but even the object is not showing as I mentioned above after adding  object node to the scene

**Comment by xthydra** [comment]
there's someone that made a blender plugin to preview a gameplay 3D scene from a blender scene and my assumption is that it might be possible that you dont need to manually write every materials to assign a texture.

take a look at https://github.com/rlofc/scene-viewer/blob/master/src/SceneViewer.cpp

i'm sorry if i confuse you but it's hard for me to sort all that information.

**Comment by deep4U** [comment]
thank you xthydra
found the previous issue by using the viewer fbx was also showing blank
mysteriously blender is exporting my 3ds into a fbx which is blank which even blender is showing as blank
So I used AutoDesk through wine and converted my 3ds model to fbx now I can see the fbx using the viewer but when I use gameplay-encoder resulting gpb is just 1.4 mb and is blank itself

using this command to convert the fbx  
./gameplay-encoder -oa -g HIKCharacterNode_boy_Reference animations /home/gaian/Downloads/89fbeab6c20a46fa897d23146eb0b5ad/railway^station.fbx
any clues?

**Comment by xthydra** [comment]
don't you get a ".material" out of the ".fbx" by using the encoder?
you can then load the material by invoking "model->setMaterial("filePath");"

**Comment by deep4U** [comment]
[gameplay-ex.zip](https://github.com/gameplay3d/GamePlay/files/261081/gameplay-ex.zip)

**Comment by deep4U** [comment]
the railway^station.fbx and railway^station.3ds files are the 3ds and fbx files I am refering to

**Comment by deep4U** [comment]
no I did not get any such .material file

**Comment by deep4U** [comment]
and even though it should atleast show the mesh with wire-frame right?

**Comment by deep4U** [comment]
it is showing properly in scene-viewer though 
m still trying to figure it out as I need proper pipeline between my scene and object model creation tool (blender) and my code

**Comment by xthydra** [comment]
a model without any materials would display as a black color and so you would need to set the background color as another color to see it

**Comment by deep4U** [comment]
found model file I think it gets generated in build/bin/linux as .material and gpb as .gpb when we open scene-viewer copied them to scene.gpb and scene.material and confirmed again by opening them through scene-viewer but now when I load them in my code adding the model->setMaterial("filePath"); I see blank screen

**Comment by deep4U** [comment]
also tried building android app of scene-viewer with ndk-build and ant debug
ndk-build returns 
Android NDK: Check that ../../GamePlay/gameplay/android/obj/local/armeabi-v7a/libgameplay.a exists  or that its path is correct   
/home/gaian/android-ndk-r11c/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.


but there is libgameplay.so not .a

**Comment by deep4U** [comment]
found something fishy
loaded the gpb as a scene through bundel and got as below
there parameters are in .material files so I suppose I need to select or change some specific vertex and fragment shaders to load the color parameter?
bind -- Material parameter for uniform 'u_inverseTransposeWorldViewMatrix' not found in effect: 'res/shaders/colored.vert;res/shaders/colored.frag;'.
bind -- Material parameter for uniform 'u_ambientColor' not found in effect: 'res/shaders/colored.vert;res/shaders/colored.frag;'.
bind -- Material parameter for uniform 'u_ambientColor' not found in effect: 'res/shaders/colored.vert;res/shaders/colored.frag;'.
bind -- Material parameter for uniform 'u_ambientColor' not found in effect: 'res/shaders/colored.vert;res/shaders/colored.frag;'.
bind -- Material parameter for uniform 'u_ambientColor' not found in effect: 'res/shaders/colored.vert;res/shaders/colored.frag;'.




and when I load in method discussed above I don't get these errors but it is blank

**Comment by deep4U** [comment]
[ex.zip](https://github.com/gameplay3d/GamePlay/files/261205/ex.zip)

this is my res folder maybe you can find if the shaders being used are not supporting material I did see that colored. shaders/colored.frag fragment shader does define the ver3 parameter with same name but does not use it in calculating color of vortices's

**Comment by xthydra** [comment]
the only thing i can tell you at this point is to take a look at the samples and take breaks to sort what your learned.

**Comment by deep4U** [comment]
It is working now but the MATERIALS ARE NOT LOOKING SAME as the fbx file looks
Still getting 
bind -- Material parameter for uniform 'u_ambientColor' not found in effect: 'res/shaders/colored.vert;res/shaders/colored.frag;'.

The gpb and material files are exactly from scene viewer that is confirmed they get generated in build/bin/linux with names .gpb and .material as hidden files when we use scene viewer in blender
Took those file and added scene.gpb as a object to scene of railstation.gpb as below also added camera and light

Bundle* bundle = Bundle::create("res/scene.gpb");
Scene* sce= bundle->loadScene();
Node* nodeengein = sce->getFirstNode();
_scene = Scene::load("res/railstation.gpb");
_scene->addNode(nodeengein);
SAFE_RELEASE(bundle);
SAFE_RELEASE(sce);
Camera* camera = Camera::createPerspective(45.0f, getAspectRatio(), 1.0f, 10.0f);
 cameraNode = _scene->addNode("camera");
// Attach the camera to a node. This determines the position of the camera.
cameraNode->setCamera(camera);
// Make this the active camera of the scene.
_scene->setActiveCamera(camera);
SAFE_RELEASE(camera);
// Move the camera to look at the origin.
cameraNode->translate(-10.9f,0.9f,0.3f);
cameraNode->rotateY(MATH_DEG_TO_RAD(-90.25f));
// Create a white light.
Light* light = Light::createPoint(3.9f, 7.9f, 5.2f,1000000000000000.0f);
Node* lightNode = _scene->addNode("light");
lightNode->setLight(light);
SAFE_RELEASE(light);
lightNode->translate(0,0,0);

**Comment by xthydra** [comment]
you can try adding 
"uniform vec3 u_ambientColor;
uniform vec4 u_diffuseColor;"

inside colored.vert...maybe it's going to change something

**Comment by deep4U** [comment]
those two lines are already there 
you can check in ex.zip the gpb and material files are changed though the shader is same 
I found that these parameters are not being used in void main()
of the shader I dont know shader language enough to understand where and how to use the vector uniform parameters in the shader.

**Comment by deep4U** [comment]
ok my bad if checked frag instead of vert

**Comment by deep4U** [comment]
Found one issue and solved If we want to add new gpb with multiple drawable subobjects(nodes)
Have to go through each node but I got seg fault if I try to recurse into all nodes with getfirstnode and getnext due to null nodes as well as nodes that are not drawable maybe?
So got workaround to add only nodes with names that I know are drawable  and translated and rotated them in the recursion itself.

Node* nodeengein1;// = sce1->getFirstNode();
char* n[6];//=NULL;
//n[0]=nodeengein1;
n[0]="Truck";
n[1]="Truck1";
n[2]="body";
n[3]="exterior";
n[4]="interior";
n[5]="interior1";
for(int i=0;i<6;i++)
{
nodeengein1=sce1->findNode(n[i],true,true);
if(nodeengein1!=NULL && nodeengein1->getId()!=NULL && n[i]!=NULL)
{
gameplay::print("%s is node id \n\n",nodeengein1->getId());
if(nodeengein1->isEnabled())
{gameplay::print("\n\nenabled indeed");}
else
{gameplay::print("\n\nnot enabled");}
//n[i]=sce1->getNext();
gameplay::print("%f %f %f is the trans of 1111111111eng",nodeengein1->getTranslation().x,nodeengein1->getTranslation().y,nodeengein1->getTranslation().z);
nodeengein1->scale(0.1);
nodeengein1->translate(-2.2f,-0.6f,0.3f);
//nodeengein->translate(-1.0f,0.3f,0.7f);
nodeengein1->rotateY(MATH_DEG_TO_RAD(90.0f));
//n[i]=nodeengein1;
gameplay::print("adding now");

_scene->addNode(nodeengein1);
gameplay::print("added");
//n[i]=sce1->getNext();
gameplay::print("next");
}

This is doing what I wanted to do In my first question thanks

**Comment by xthydra** [comment]
you should close the issue if your issue is resolved
