### ISSUE TITLE
Shadow mapping example

### ISSUE THREAD

**Issue by VinnyVicious** [gameplay3d/GamePlay#1833]
It would be nice to have an example of shadow mapping in the engine. VSM or PSSM, or even CSM.

http://http.developer.nvidia.com/GPUGems3/gpugems3_ch10.html
http://http.developer.nvidia.com/GPUGems3/gpugems3_ch08.html

**Comment by seanpaultaylor** [comment]
Specialty gems techniques will not be part of the examples.
