### ISSUE TITLE
JS instead of Lua? 

### ISSUE THREAD

**Issue by VinnyVicious** [gameplay3d/GamePlay#1837]
Why are you switching from Lua to JS? It's much slower!

https://github.com/r-lyeh/scriptorium

**Comment by diego3** [comment]
Great ponit, i'm just thinking about benchmaking for javascrit V8

**Comment by seanpaultaylor** [comment]
You really should have a v8 js benchmark in there that is up to date. They are essentially neck-neck and adding Typescript gives you a typecompiler and great cross platform IDE scripting tools like vs code.
