### ISSUE TITLE
Smart pointer support

### ISSUE THREAD

**Issue by SuperWangKai** [gameplay3d/GamePlay#1839]
I've been playing with gameplay for quite a long time. I found that the Ref classes are hard to maintain and developer has to pay a lot of attention on the life cycle of every Ref otherwise the Refs will leak. 

I wonder if we can have **strong pointer** and **weak pointer** to enhance the ref counting machanism. Maybe we should not wait until _'next-gen' gameplay_ to have this feature.

Thanks!

**Comment by xthydra** [comment]
i don't understand how a pointer can be weak or strong, can you elaborate on what's the difference between a weak and a strong pointer and where you would want these pointers to be used.
do you have any example of how these types of reference are used inside a program?

**Comment by SuperWangKai** [comment]
Hi @xthydra 
FYI,
https://en.wikipedia.org/wiki/Smart_pointer#shared_ptr_and_weak_ptr
https://github.com/urho3d/Urho3D/blob/1e2baf7d7f7c392d6f8f8acb0444a73823297451/Source/Urho3D/Container/Ptr.h

**Comment by seanpaultaylor** [comment]
The Ref class is actually a smart pointer. I guess what you are asking is to make the API in a way that is more explicit in passing parameters around. The only issue is that the api becomes quite different. Not all people enjoy using new c++11 standards. If I were to change it. I would consider using C++11 std::shared_ptr. 
http://en.cppreference.com/w/cpp/memory/shared_ptr

I am considering the implication of this. I don't see any value in replacing the current smart pointer Ref class with another only you referenced.

**Comment by SuperWangKai** [comment]
What I mean is that the smart pointers will largely do help to maintain the life cycle of the Ref object. Just like ComPtr in windows which helps the com object maintain the reference count. Currently, in gameplay, we have to carefully handle the release and add ref.
