### ISSUE TITLE
Simplify node hierarchy in the scene

### ISSUE THREAD

**Issue by SuperWangKai** [gameplay3d/GamePlay#1840]
In the current implimentation of gameplay, we can store child nodes in both **Scene** and **Node**. 

There are many lines of duplicated code in both Scene and Node. And everytime we want to handle nodes operations we have to treat Scene children and Node's children **differently**, which is complicated and error prone.

We can use a **dummy node** as the only root node of Scene or we can treat Scene as a **special node** (Scene inherits Node). Thus, we can largely simplify the scene node management and unify the node operations and get rid of the duplicated code inside class Scene.

**Comment by SuperWangKai** [comment]
Additinally, we can use double linked list or similar container to simplify the nodes management. Currently, we have to handle pointers very carefully. (e.g. _nextSibling, _prevSibling, _firstNode,  _lastNode, etc.)

**Comment by SuperWangKai** [comment]
To explain the issue better, I have an example as follows. 

**insertNode** is an function that inserts a node to some position of the node list (It's a little time consuming, but it's still useful in some cases, since we do care about node order sometimes). And I have another similar function in the Node class, which named **insertChild**. 

You could see the complication here, though I haven't tested them yet...

```c++
void Scene::insertNode(Node* node, unsigned int index)
{
	GP_ASSERT(node);

	bool sameScene = false;

	if (node->_scene == this)
	{
		if (node->getIndex() == index)
			return;
		else
		{
			sameScene = true;
			node->addRef();
			node->_scene->removeNode(node);
		}
	}

	if (index >= getNodeCount())
		return addNode(node);

	if (!sameScene)
		node->addRef();

	// If the item belongs to another hierarchy, remove it first.
	if (node->getParent())
	{
		node->getParent()->removeChild(node);
	}
	else if (node->_scene)
	{
		node->_scene->removeNode(node);
	}

	if (!_firstNode || !_lastNode)
	{
		_firstNode = node;
		_lastNode = node;
	}
	else
	{
		Node* n = getNodeByIndex(index);
		GP_ASSERT(n);
		if (n->_prevSibling)
			n->_prevSibling->_nextSibling = node;

		node->_prevSibling = n->_prevSibling;

		node->_nextSibling = n;
		n->_prevSibling = node;

		if (_firstNode == n)
			_firstNode = node;
	}

	node->_scene = this;
	
	++_nodeCount;

	Node::insertNodeKeyMap(node);
}
```

Thanks!
Kai

**Comment by seanpaultaylor** [comment]
There was no insertNode for a reason. The goal is to not have to worry about order.
You should be focusing instead on using an alternative mechanism to tag or group  items instead.
