### ISSUE TITLE
[Android] How to use GamePlay with GLSurfaceView?

### ISSUE THREAD

**Issue by aceding** [gameplay3d/GamePlay#1845]
I want to use gameplay with a GLSurfaceView, now have no idea with it.

**Comment by dumganhar** [comment]
GamePlay uses nativeActivity and create EGL environment in native code.
It doesn't have GLSurfaceView which is a Java class instance.

**Comment by aceding** [comment]
If I want to use gameplay with GLSurfaceView, what I can do to make it work?

发自我的 iPhone

**Comment by devindi** [comment]
+1. I would like to use GamePlay through GLSurfaceView

**Comment by seanpaultaylor** [comment]
Ask this on the community groups. This is not what issues are for.
