### ISSUE TITLE
CMakeLists.txt for GamePlay-deps doesn't support Cygwin.

### ISSUE THREAD

**Issue by JontomXire** [gameplay3d/GamePlay#1849]
As the very first line you need to add:

set(CMAKE_LEGACY_CYGWIN_WIN32 0) # Remove when CMake >= 2.8.4 is required

You need to change:

if(LINUX OR ANDROID)
    add_custom_command(
        OUTPUT ${GAMEPLAY_DEPS}

to:

if(LINUX OR ANDROID OR CYGWIN)
    add_custom_command(
        OUTPUT ${GAMEPLAY_DEPS}

**Comment by seanpaultaylor** [comment]
No plans to support cygwin at this time.
