### ISSUE TITLE
How Can I use MVP Matrix in Gameplay

### ISSUE THREAD

**Issue by shishaozheng** [gameplay3d/GamePlay#1853]
I have got a MVP Matrix from some Image identification SDK， and now I wanna use the  MVP Matrix to draw a 3d model with gameplay3d  so that the model display in the Image's position, But I can't find the API which can accept the  MVP Matrix as a parameter. What should I do to use the MVP Matrix with gameplay3d

**Comment by seanpaultaylor** [comment]
Ask on community groups. the Issues are for bugs.
