### ISSUE TITLE
How can I "generate" a .animation file from .fbx? 

### ISSUE THREAD

**Issue by biluncloud** [gameplay3d/GamePlay#1854]
In the character demo tutorial, it's said that:
> Once you have defined these clips in your modeling tool, you can **export** them to an .animation file for use by your application. 

But how could I generate it, I've tried to export the animation from Maya. But the export format is **.atom**, whose the format is completely different from that in **.animation** file. So does anyone know how to get this **.animation** file? Thanks a lot.

**Comment by shishaozheng** [comment]
It seems that you should define this file by yourself.

**Comment by gwald** [comment]
Yes, via a text file or hardcoded.
https://github.com/gameplay3d/GamePlay/wiki/Animation

**Comment by biluncloud** [comment]
@gwald @shishaozheng got it, thanks
