### ISSUE TITLE
Cannot Build With Intel Compiler 16.0 Update 4 On Windows 10 x64

### ISSUE THREAD

**Issue by baddestagate414** [gameplay3d/GamePlay#1855]
Everything is 100% fine when building the solution but when i launch my game or any other example the app crashes saying that cannot find the entry point of the procedure "__svml_fmodf4"

**Comment by reven86** [comment]
Did you build all gameplay-deps with Intel Compiler as well?

**Comment by baddestagate414** [comment]
yup just finished. same problem
