### ISSUE TITLE
Is there any API to convert the Rotation Matrix/Quaternion/Axis Angle to Euler Angle?

### ISSUE THREAD

**Issue by shishaozheng** [gameplay3d/GamePlay#1856]
I have a Rotation Matrix, but I wanna ignore the Z axis rotation, is the any method to convert the Rotation Matrix/Quaternion/Axis Angle to Euler Angle so that I can only use the X and Y rotation angle?

**Comment by benloong** [comment]
Definitely YES.

Quaternion to Euler angles : `Quaternion::computeEuler(float* yaw, float* pitch, float* roll)`

Euler angles to Quaternion :  `createFromEuler(float yaw, float pitch, float roll, Quaternion* dst)`
