### ISSUE TITLE
Cannot create custom control because everything is private.

### ISSUE THREAD

**Issue by JontomXire** [gameplay3d/GamePlay#1857]
Second attempt writing this after an accidental shortcut press closed the window while I was typing :(

I am trying to create a "statistics bar" control to display health, mana etc. I originally planned to make it able to be really beautiful by overriding the Control classes draw functions, but I had to abandon that plan because the Theme::Skin class, and several others, and loads of useful access funtions, are all private. So I have to use Control::drawBorders() rather than overriding it.

I am now trying to draw the bar itself, and since GamePlay3d has no capability whatsoever to draw simple geometric shapes, I am using a blank white square. However because access to the themes' list of ThemeImage data is private I have to hardcode the co-ordinates of the square in the texture. I even have to implement my own routine to convert from pixel coordinates to UV coordinates because Theme::generateUVs is private too.

Why? Why is so much of this great, highly re-usable, functionality private? It makes the UI completely non-extensible. It makes themes extremely limited. It means developers need to write copies of code that you have already implemented. And there seems to be no purpose to it. I can understand making member data private and then providing access functions, but something as simple as pixel to UV co-ordinate conversion, where no data is changed, why make that private? Especially when the SpriteBatch function exposes draw functions that require UV co-ordinates which, frankly, are a pig to deal with.

Please make more of this functionality public so we can extend Themes with additional data and access it.

**Comment by seanpaultaylor** [comment]
This is not some big extensible ui framework. Its a minimalistic game ui. It is for adding skinnable basic components together. We would actually like a few more core controls like drop down and list view.

What is sounds like you are trying to make is a "custom" form with compound controls in it. 
There is no need to make a custom control for this scenario. You simply create a "custom" form with all the basic core controls in it. You can have multiple forms on the screen so this is how the framework ui works.
The control hierarchy was made with private to block people from making mistake such as this,

BTW. In the future use the forums to ask question about architecture and features.
