### ISSUE TITLE
About running install.bat, is there something wrong with the download path  ?

### ISSUE THREAD

**Issue by JackeryShh** [gameplay3d/GamePlay#1861]
hi,  I just download the source code,my system is Windows 10, according to the guide, I run the install.bat, but it seems I can not download the gameplay-deps.zip. When I try to open the link in the bat file(https://github.com/gameplay3d/GamePlay/releases/download/v3.0.0) ,a 404 error . I find the place of  the zip file(gameplay-deps.zip) in https://github.com/gameplay3d/GamePlay/releases. I really do not know why and make me confused, Is there changed for the install.bat ?

**Comment by benloong** [comment]
It works on my Windows 10 PC. that should be a your network issue.  You could download deps directly from this link:  
https://github.com/gameplay3d/GamePlay/releases/download/v3.0.0/gameplay-deps.zip

**Comment by qq910438219** [comment]
The same thing happed before . sometime ok sometime bad . I  directly downlaoded the zip file and unziped it manually. (if  fail again, you can get a copy from 910438219@qq.com)

**Comment by JackeryShh** [comment]
yeah,I have download it  directly,it can be run . but I think something wrong with the link or bat file,thanks.
