### ISSUE TITLE
Is there any way to decompile / decode the 3d model asset files?

### ISSUE THREAD

**Issue by jonathan-werner** [gameplay3d/GamePlay#1863]
We have files that have been encoded using the Gameplay Encoder. Now we would like to decompile / decode those files to be able to get information about e.g. which animations are included in that file. You can assume that we do not have access to the original fbx files anymore. Does anybody have an idea on how we could achieve this?

**Comment by sgrenier** [comment]
There is no existing decompiler/decoder for GPB files. However, the file format is documented here: https://github.com/gameplay3d/GamePlay/blob/master/tools/encoder/gameplay-bundle.txt. It should be relatively straightforward to create a simple tool to pull the information you're after out of the bundle.

**Comment by dgough** [comment]
It might be easier to modify Bundle.cpp and have it print while it is reads
the gpb file. You could modify readNode() to print the node information and
readAnimation() to print the animation information.

**Comment by seanpaultaylor** [comment]
Ask this stuff on the community group.

**Comment by jonathan-werner** [comment]
Thanks for all your answers! And sorry for having asked it here. I will from now on use the community group for such questions.
