### ISSUE TITLE
SceneObject and Component is  Circular references

### ISSUE THREAD

**Issue by fjh658** [gameplay3d/GamePlay#1870]
nextgen branch: 

SceneObject and Component is  Circular references

**Comment by seanpaultaylor** [comment]
To solve the circular references I used a parent node with weak_ptr. The weak_ptr allows sharing but not owning an object. It’s object is created by a shared_ptr. With weak_ptr object we cannot directly use operators * and -> to access the associated memory. First we have to create a shared_ptr through weak_ptr object by calling its lock() function,  then only we can use it.  The lock() function can return empty shared_ptr if that shared_ptr is already deleted.

Let me know if you still think this is an issue and I can review.
